name: animebox
description: "Manage your Anime."
publish_to: "none"

version: 0.1.3+4

environment:
  sdk: ^3.10.1

dependencies:
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  logger: ^2.6.2
  global_configuration: ^2.0.0
  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  html: ^0.15.6
  http: ^1.6.0
  path: ^1.9.1
  uuid: ^4.5.2
  video_player: ^2.10.1
  media_kit: ^1.2.3
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  collection: ^1.19.1
  js_unpack: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
